name: Deploy to MLRS
on:
  push:
    branches:
      - deploy-action
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Open VPN
      run: sudo apt-get install openvpn
      
    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: '10.249.1.100'
        FILE_OVPN: '.github/vpn/config.ovpn'
      env:
        CA_CRT: ${{ secrets.CA_CRT }}
        USER_CRT: ${{ secrets.USER_CRT }}
        USER_KEY: ${{ secrets.USER_KEY }}
        
    - name: Check Connect VPN
      run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      
    # - name: Add host key to known_hosts
    #   run: mkdir -p ~/.ssh && ssh-keyscan 10.249.1.100 >> ~/.ssh/known_hosts

    - name: Create SSH folder
      run: mkdir -p ~/.ssh && chmod 700 ~/.ssh
      
    - name: Copy SSH settings
      run: cp .github/vpn/config.ssh ~/.ssh/config && chmod 600 ~/.ssh/config
      
    - name: Run deploy script
      run: ./deploy.sh
      
    - name: Close VPN
      if: always()
      run: sudo killall openvpn
