name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        mongodb-version: [3.2, 4.0, 4.2]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: superchargejs/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Populate database
      run: mongoimport test/data/*.json

    - name: Install
      run: npm ci

    - name: Create server-config.js
      run: mv server-config.sample.js server-config.js

    - name: Run tests
      run: npm test
      env:
        CI: true
